### ISSUE TITLE
A topic with multiple partitions won't get dedicated consumer members in consumer group for each partition

### ISSUE THREAD

**Issue by bentcoder** [IBM/sarama#2899] opened 2024-05-16 10:39 UTC
##### Description

Hi,

My topic `errors-topic` has 3 partitions. When I create a _consumer group_ for the topic, I see only 1 consumer member being created and assigned to all 3 partitions. I thought each partitions would get their own consumer member for concurrent consumption but this doesn't seem possible at the moment.

I assume this behaviour is going to cause performance issue when consuming messages because there is only 1 member doing everything. I don't see any configuration option to force creating a dedicated members for each partitions. Is this a bug or intentional design for consumer groups?

For the time-being, as an experimental act, if I call `kfk.CreateConsumerGroup("errors-topic")` in a `for` loop 3 times, each partition will get their own consumers but I am not sure if this is right way of working with the API.

Thank you in advance

##### Versions

| Sarama | Kafka | Go  |
| ------ | ----- | --- |
|   v1.43.2     |   v3.3.2    |  1.22   |

##### Configuration

```go
func main() {
	kfk := New([]string{":9093"})
	kfk.CreateConsumerGroup("errors-topic")
}
```

```go
type Kafka struct {
	brokers []string
	config  *sarama.Config
}

func New(brokers []string) Kafka {
	cfg := sarama.NewConfig()
	cfg.Consumer.Return.Errors = true
	cfg.Consumer.Offsets.Initial = sarama.OffsetOldest

	return Kafka{
		brokers: brokers,
		config:  cfg,
	}
}

func (k Kafka) CreateConsumerGroup(topic string) error {
	grp, err := sarama.NewConsumerGroup(k.addrs, topic+"-group", k.config)
	if err != nil {
		return err
	}

	go func() {
		for err := range grp.Errors() {
			fmt.Println("ERROR", err)
		}
	}()

	handler := handler{}

	for {
		err := grp.Consume(context.Background(), []string{topic}, &handler)
		if err != nil {
			fmt.Printf("error in consumer handler: %v", err)
		}
	}
}

type handler struct{}
func (*handler) Setup(sarama.ConsumerGroupSession) error   { return nil }
func (*handler) Cleanup(sarama.ConsumerGroupSession) error { return nil }
func (*handler) ConsumeClaim(sess sarama.ConsumerGroupSession, claim sarama.ConsumerGroupClaim) error {
	for msg := range claim.Messages() {
		// ...
		sess.MarkMessage(msg, "")
	}

	return nil
}
```

##### Additional Context

I did a bit of benchmarking on consumption speed, and the results seem to be very very similar for both singular and multiple members versions. I am not even sure if it is worth trying to spin up multiple consumer members. I didn't expect this :(

---

### This is what I am currently getting

![1](https://github.com/IBM/sarama/assets/8837278/b47044bf-0c58-4b03-b345-1295646720c1)

### This is what would get if I called `CreateConsumerGroup` in a loop

![2](https://github.com/IBM/sarama/assets/8837278/0c375ae2-8283-48fa-884b-b58a2f06a6c0)

**Comment by puellanivis** [comment] 2024-05-17 07:59
The partitions are distributed among the number of consumers in the consumer group.

If there is only one consumer in the consumer group then the proper distribution of 3 partitions is all three partitions assigned to the one consumer.

**Comment by bentcoder** [comment] 2024-05-17 10:11
The image with red marks resulted from the the code I posted above. As we can see there is only 1 consumer (member) in the consumer group (`errors-topic-group`) hence all 3 partitions of the topic (`errors-topic`) are assigned to this single consumer.

So the question is, using this client library, what is the correct way of creating dedicated consumers (3 members) in same consumer group so that each partitions gets their own consumers please?

The reason why I am asking this is because; the image with green marks resulted from calling `CreateConsumerGroup` function in a loop 3 times which seems to be achieving what I am asking here. **However** it doesn't make sense to call `NewConsumerGroup` within this loop as it creates the consumer group (as far as its name goes). All we need is to create consumers and attach it to this group. Am I missing something with this library!? I cannot take `NewConsumerGroup` out of loop otherwise I don't get 3 dedicated consumers. I am a bit dazzled here with library usage.

**Comment by puellanivis** [comment] 2024-05-17 10:58
1) There is no performance benefit to having one service connecting 3 times to the same consumer group. Whether the partitions are distributed to three internal consumers, or to only one consumer, there will still only be one machine handling the whole work load anyways. Client libraries take care of efficiently handling multiple partitions when allocated them as its fair share.
2) We don’t want individual services to start up a separate consumer per partition, because then if one had two machines connecting, then there would be twice as many connections as partitions, and so only half of the consumers would actually be allocated a partition, and doing any work. This also means there is the chance that all three partitions could be allocated to one machine, and now the horizontal scaling has done nothing since everything is still allocated all to one service.

You’re also misinterpreting what `NewConsumerGroup` does. This connects one consumer to a consumer group, but if that group id already exists on the kafka server, then it simply joins that consumer to that existing consumer group. The correct way to join three consumers to the same consumer group, whether on one machine, or multiple machines is to use the `NewConsumerGroup` function.

**Comment by bentcoder** [comment] 2024-05-17 12:04
So what I understand from your comment is, my code is perfectly fine. Am I correct to assume this?

**Comment by puellanivis** [comment] 2024-05-17 17:28
Yes, your code is perfectly fine, and the behavior you’re seeing is the intended behavior. (And additionally it would be suboptimal to build three consumers on one client, just because there are three partitions.)

**Comment by bentcoder** [comment] 2024-05-17 18:11
Thank you for the help.

**Closed** 2024-05-17 18:11 UTC
